name: macOS

on:
  push:
    branches:
      - github-action-tests
      - qt-6.2-cmake-cpp-17

jobs:
  xcode:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [13.2]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Setting up the Keychain Certificate
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
          PKG_CONFIG_PATHS_FOR_CMAKE: "/usr/local/opt/zlib;/usr/local/opt/openssl@3;/usr/local/opt/qt;/usr/local/opt/libarchive"
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > Certificate.p12
          security create-keychain -p $MACOS_KEYCHAIN_PWD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $MACOS_KEYCHAIN_PWD build.keychain
          security import Certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_KEYCHAIN_PWD build.keychain
      - name: Updating Homebrew
        run: brew update --preinstall
      - name: Preparing the Requirements
        run: brew install automake bison flex cmake pkg-config brotli ninja conan
      - name: Configuring Conan
        run: |
          conan profile new default --detect
          conan profile show default
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.3'
          host: 'mac'
          target: 'desktop'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          setup-python: 'true'
          set-env: 'true'
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build -G Ninja -D GITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DSIGN_AT_BUILD_TIME=OFF -DTIMESTAMP_AT_BUILD_TIME=OFF -DINSTALL_R_MODULES=OFF
      - name: Build
        run: cmake --build build