name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        name: Preparing the MSYS2 Environment
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-jsoncpp
            bison
            flex
            libtool
            mercurial
      - shell: msys2 {0}
        run: |
          uname -a
          pacman -Q
      - shell: powershell
        run: msys2 -c 'uname -a'
      - shell: cmd
        run: msys2 -c 'uname -a'