name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt-version: [6.2]

    steps:
      - uses: msys2/setup-msys2@v2
      - name: MSYS2 Requirements
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-jsoncpp
            bison
            flex
            libiconv
            libtool
            mercurial