name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          cached: 'false'
          set-env: 'true'
      - uses: msys2/setup-msys2@v2
        name: Preparing the MSYS2 Environment
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-jsoncpp
            bison
            flex
            libtool
            mercurial
      - name: Installing Conan
        run: |
          pip install wheel setuptools
          pip install conan --upgrade
          conan --version
      - name: Configuring Conan Profile
        run: |
          conan profile new default --detect
          conan profile show default
          conan profile update settings.compiler.version=16 default
          conan profile update settings.compiler.runtime=MDd default
          conan profile update settings.build_type=Debug default
          conan profile show default
      - uses: actions/checkout@v2
        name: Cloning JASP
      - name: Configuring Conan
        run: conan install .
      - name: Pre-configuring the JASP Desktop
        run: cmake -S . -B build -DGITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DGITHUB_ACTION_BUILD=ON -DINSTALL_R_MODULES=ON -DCONAN_DISABLE_CHECK_COMPILER=ON -DCMAKE_PREFIX_PATH="$Qt6_DIR"
      - name: Configuring R-Interface
        run: |
          cd R-Interface
          cmake -S . -B build -D -DJASP_BINARY_DIR=../build
      - name: Building R-Interface
        run: |
          cmake --build build
          cd ..
      - name: Re-configuring JASP Desktop
        run: cmake -S . -B build -D GITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DGITHUB_ACTION_BUILD=OFF -DINSTALL_R_MODULES=ON -DR_INTERFACE_BINARY_DIR=R-Interface/build
      - name: Building JASP
        run: cmake --build build