name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        name: Preparing the MSYS2 Environment
        with:
          msystem: mingw64
          update: true
          install: >-
            boost
            jsoncpp
            bison
            flex
            libiconv
            libtool
            mercurial
          run:
            pacman -Q