name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        name: Preparing the MSYS2 Environment
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-jsoncpp
            bison
            flex
            libtool
            mercurial
      - name: Installing Conan
        run: |
          pip install wheel setuptools
          pip install conan --upgrade
      - name: Configuring Conan Profile
          conan profile new default --detect
          conan profile show default
      - uses: actions/checkout@v2
        name: Cloning JASP
      - name: Configuring Conan
        run: conan info .