name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt-version: [6.2]

    steps:
      - uses: msys2/setup-msys2@v2
      - name: MSYS2 Requirements
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-jsoncpp
            bison
            flex
            libiconv
            libtool
            mercurial
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          cached: 'false'
          set-env: 'true'

      - name: Install Conan
        uses: turtlebrowser/get-conan@main
      - uses: actions/checkout@v2
      - name: Configuring Conan
        run: conan install . --build=missing
      # - name: Configuring JASP Desktop
      #   run: cmake -S . -B build -D GITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DINSTALL_R_MODULES=OFF -DR_INTERFACE_BINARY_DIR=R-Interface/build
      # - name: Configuring R-Interface
      #   run: |
      #     cd R-Interface
      #     cmake -S . -B build -D -DJASP_BINARY_DIR=../build
      # - name: Building R-Interface
      #   run: cmake --build build
      # - name: Building JASP Desktop
      #   run: |
      #     cd ..
      #     cmake --build build