name: Windows

on:
  push:
    branches:
      - wip-windows-cmake-build

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt-version: [6.2]

    steps:
      - uses: msys2/setup-msys2@v2
      - name: MSYS2 Requirements
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-jsoncpp
            bison
            flex
            libiconv
            libtool
            mercurial
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          cached: 'false'
          set-env: 'true'

      - name: Install Conan
        run: pip install conan
      - name: Conan version
        run: conan --version
      - uses: actions/checkout@v2
      - name: Configuring Conan
        run: conan install . --build=missing